sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t blog3 .

script:
  - docker run --rm -v "`pwd`":/app blog3 ./bin/publish
  - sudo rm -rf .ruby-version .dockerignore .travis.yml content/ bin/ Dockerfile Gemfile* Guardfile layouts lib Makefile nanoc.gh-pages.yaml nanoc.yaml output Rules template tmp yarn.lock
  - cp -r docs/* `pwd`

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  on:
    branch: master
  verbose: true
